# Gradients 

In this section, we are going to learn about the automatic computation of gradients in PyTorch, and how to use them for parameter optimization in machine learning algorithms.

# What is a Gradient in pytorch?

A gradient in PyTorch is a vector of partial derivatives of a function with respect to its input variables. It is used to calculate the direction and magnitude of the steepest ascent or descent of a function at a particular point. 

In deep learning, gradients are used to update the parameters of a neural network during the training process, by backpropagating the error and adjusting the weights and biases accordingly. 

PyTorch provides automatic differentiation, which allows for efficient computation of gradients without having to manually define and calculate them. This makes it easier to build and train complex neural networks in PyTorch.

In [3]:
import torch

# Create a tensor and tell PyTorch that we want to compute the gradient
x = torch.tensor([3.0], requires_grad=True)

# Define a function
y = x**2

# Compute the gradient
y.backward()

# Print the gradient
print(x.grad)   # Output: tensor([6.])

tensor([6.])


In [4]:
# data
X = torch.tensor([0.5, 0.9, 1.4, 1.8], requires_grad=True)
Y = torch.tensor([2.0, 3.8, 5.0, 7.2], requires_grad=True)

# Initialize parameters
a = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

learning_rate = 1e-2
for i in range(100):
    # Make a prediction
    predictions = a * X + b
    
    # Compute the loss
    loss = torch.mean((predictions - Y)**2)
    
    # Compute the gradients
    loss.backward()
    
    # Update the parameters using the gradients
    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        
    # Zero the gradients
    a.grad.zero_()
    b.grad.zero_()

print(a, b)  # Output: optimized parameters a and b

tensor([2.7157], requires_grad=True) tensor([1.4730], requires_grad=True)


In [5]:
# Create a tensor
x = torch.tensor([1., 2., 3.], requires_grad=True)

# Define a function
y = torch.sum(x ** 2)

# Compute the gradient
y.backward()

# Show the gradient
print(x.grad)   # Output: tensor([2., 4., 6.])

tensor([2., 4., 6.])
